In [22]:
import pandas as pd
colnames=['video_id', 'middle_frame_timestamp', 'x1', 'x2', 'y1', 'y2', 'action_id', 'person_id'] 
kinetics_train = pd.read_csv('/data1/hongn/ava_kinetics_v1_0/kinetics_train_v1.0.csv', names=colnames, header=None)

In [17]:
len(kinetics_train['video_id'].unique())

136842

## AVA

In [22]:
import pandas as pd
colnames=['video_id', 'middle_frame_timestamp', 'x1', 'x2', 'y1', 'y2', 'action_id', 'person_id'] 
val_ava = pd.read_csv('/data1/hongn/ava_kinetics_v1_0/ava_val_v2.2.csv', names=colnames, header=None).dropna()
val_ava.head()

video_id  middle_frame_timestamp     x1     x2     y1     y2  action_id  \
0  1j20qq1JyX4                     902  0.002  0.118  0.714  0.977       12.0   
1  1j20qq1JyX4                     902  0.002  0.118  0.714  0.977       79.0   
2  1j20qq1JyX4                     902  0.444  0.054  0.992  0.990       12.0   
3  1j20qq1JyX4                     902  0.444  0.054  0.992  0.990       17.0   
4  1j20qq1JyX4                     902  0.444  0.054  0.992  0.990       79.0   

   person_id  
0        1.0  
1        1.0  
2        0.0  
3        0.0  
4        0.0

In [41]:
video_ids = list(set(val_ava.video_id))

In [42]:
i = 54
vid_i = val_ava[val_ava.video_id == video_ids[i]]
action_i = list(set(val_ava[val_ava.video_id == video_ids[i]].action_id))
sub_vid_act_i = val_ava[val_ava.video_id == video_ids[i]][val_ava.action_id == action_i[0]]

/tmp/ipykernel_2158938/1136156252.py:4: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  sub_vid_act_i = val_ava[val_ava.video_id == video_ids[i]][val_ava.action_id == action_i[0]]


In [43]:
video_ids[i]

'ZosVdkY76FU'

In [44]:
sub_vid_act_i

video_id  middle_frame_timestamp     x1     x2     y1     y2  \
133942  ZosVdkY76FU                    1085  0.265  0.285  0.669  0.985   
133945  ZosVdkY76FU                    1086  0.021  0.038  0.720  0.969   
133987  ZosVdkY76FU                    1102  0.847  0.182  0.997  0.754   
134894  ZosVdkY76FU                    1153  0.132  0.254  0.413  0.975   
134918  ZosVdkY76FU                    1154  0.201  0.343  0.520  0.990   
135347  ZosVdkY76FU                    1235  0.139  0.379  0.485  0.955   
136517  ZosVdkY76FU                    1503  0.182  0.232  0.454  0.822   
136525  ZosVdkY76FU                    1505  0.275  0.011  0.744  0.968   
136528  ZosVdkY76FU                    1506  0.544  0.134  0.831  0.970   
136530  ZosVdkY76FU                    1507  0.301  0.110  0.794  0.939   
136889  ZosVdkY76FU                    1545  0.740  0.386  0.860  0.742   
139086  ZosVdkY76FU                    1729  0.378  0.251  0.614  0.621   
139094  ZosVdkY76FU                    1730  0.229  0.278  0.478  0.654   
139108  ZosVdkY76FU                    1731  0.182  0.315  0.496  0.633   

        action_id  person_id  
133942        1.0       67.0  
133945        1.0       67.0  
133987        1.0       84.0  
134894        1.0      178.0  
134918        1.0      180.0  
135347        1.0      264.0  
136517        1.0      330.0  
136525        1.0      337.0  
136528        1.0      338.0  
136530        1.0      339.0  
136889        1.0      400.0  
139086        1.0      724.0  
139094        1.0      727.0  
139108        1.0      728.0

In [27]:
from pytube import YouTube
from moviepy.video.io.VideoFileClip import VideoFileClip

# Define video URL and download path
video_url = "https://www.youtube.com/watch?v=YOUR_VIDEO_ID"
output_path = "./downloads"

# Download video using pytube
yt = YouTube(video_url)
video_stream = yt.streams.get_highest_resolution()
video_filepath = video_stream.download(output_path=output_path)

print(f"Video downloaded to: {video_filepath}")

# Define start and end times (in seconds)
start_time = 1667  # e.g., Start at 30 seconds
end_time = 1754    # e.g., End at 60 seconds

# Trim the video using moviepy
output_trimmed_path = f"{output_path}/trimmed_video.mp4"
with VideoFileClip(video_filepath) as video:
    trimmed_clip = video.subclip(start_time, end_time)
    trimmed_clip.write_videofile(output_trimmed_path, codec="libx264")

print(f"Trimmed video saved to: {output_trimmed_path}")


{1.0,
 6.0,
 10.0,
 11.0,
 12.0,
 14.0,
 17.0,
 36.0,
 40.0,
 58.0,
 59.0,
 67.0,
 69.0,
 74.0,
 79.0,
 80.0}

## SSv2 Everything

In [20]:
import glob
import os
ssv2_dir = glob.glob('/data1/hongn/SSv2/frames/*')
list_empty_folder = []
for path in ssv2_dir:
    if len(os.listdir(path)) == 0:
        list_empty_folder.append(path)

In [ ]:
['/data1/hongn/SSv2/frames/123178', '/data1/hongn/SSv2/frames/123156']
list_empty_folder

['/data1/hongn/SSv2/frames/123178', '/data1/hongn/SSv2/frames/123156']

In [66]:
#TimeSFormer AVA lavel, turn out, it does not need to be processed
import pandas as pd
val = pd.read_csv('/data1/hongn/SSv2/labels/val.csv')
col_merge = 'original_vido_id video_id frame_id path labels'
val[col_merge.split(' ')] = val[col_merge].str.split(' ', expand=True)
val = val.drop(col_merge, axis=1)
# val.to_csv('/data1/hongn/SSv2/labels/train.csv', index=False, header=True)
# val.head()

In [67]:
from tqdm import tqdm

list_empty_folder = []

for name in tqdm(val.path):
    if(os.path.isfile('/data1/hongn/SSv2/frames/' + name) == False):
        list_empty_folder.append(name)

100%|██████████| 3018451/3018451 [01:19<00:00, 37919.14it/s] 


In [ ]:
list_empty_folder

In [68]:
folder_redo = [name.split('/')[0] for name in list_empty_folder]
set(folder_redo)

set()

## HAA500

In [1]:
import pandas as pd
train = pd.read_csv('/data1/hongn/kinetics-dataset/k400/train.csv')
train.head()

/data1/hongn/kinetics-dataset/k400/train/8mbN0ubh0q8_000000_000010.mp4  101
0  /data1/hongn/kinetics-dataset/k400/train/9bfc-...                       17
1  /data1/hongn/kinetics-dataset/k400/train/VV0KA...                      167
2  /data1/hongn/kinetics-dataset/k400/train/sWCnx...                      318
3  /data1/hongn/kinetics-dataset/k400/train/Am6c9...                      356
4  /data1/hongn/kinetics-dataset/k400/train/pC1hX...                      231

In [3]:
train_haa500 = pd.read_csv('/data1/hongn/haa500/raw/climb_icecliff.txt')
train_haa500.head()

https://www.youtube.com/watch?v=Uo_sDYOvW98  113.19  116.11  1  1.1
0  https://www.youtube.com/watch?v=79s5BD0301o  348.50  351.50  1    1
1  https://www.youtube.com/watch?v=1syox_mjE6s  124.41  127.13  0    1
2  https://www.youtube.com/watch?v=OnV0XbwSAAM  423.48  426.39  0    2
3  https://www.youtube.com/watch?v=Xp83UFuKxyE  616.31  619.07  1    1
4  https://www.youtube.com/watch?v=-iDBPhSc2mU  130.50  133.15  0    1

In [85]:
from glob import glob
import numpy as np

action_folders = glob('/data1/hongn/haa500/video/*')
label_nameidx_map = pd.DataFrame(columns=['label_name', 'label_index'])
# all_data = pd.DataFrame(columns=['paths', 'labels'])
# actions
action_paths = []
labels = []
for i in range(len(action_folders)):
    action_name = action_folders[i].split('/')[-1]
    # print(action_name)
    label_nameidx_map.loc[i] = [action_name, i]
    actioni_paths = glob(f'/data1/hongn/haa500/video/{action_name}/*')
    action_paths.append(actioni_paths)
    labels.append(np.ones(len(actioni_paths)) * i)

action_paths = np.array(action_paths).flatten()
labels = np.array(labels).flatten().astype(int)

In [86]:
from sklearn.model_selection import train_test_split
X_trainval, X_test, y_trainval, y_test = train_test_split(action_paths, labels, test_size=0.33, random_state=42, shuffle=True)
X_train, X_val, y_train, y_val = train_test_split(X_trainval, y_trainval, test_size=0.33, random_state=42, shuffle=True)

In [95]:
train = pd.DataFrame(np.stack([X_train, y_train], axis=1), columns=['paths', 'labels'])
val = pd.DataFrame(np.stack([X_val, y_val], axis=1), columns=['paths', 'labels'])
test = pd.DataFrame(np.stack([X_test, y_test], axis=1), columns=['paths', 'labels'])

label_nameidx_map.to_csv('/data1/hongn/haa500/label_nameidx_map.csv',index=False, header=False)
train.to_csv('/data1/hongn/haa500/train.csv',index=False, header=False)
val.to_csv('/data1/hongn/haa500/val.csv',index=False, header=False)
test.to_csv('/data1/hongn/haa500/test.csv',index=False, header=False)

In [90]:
np.stack([X_train, y_train], axis=1)

array([['/data1/hongn/haa500/video/basketball_shoot/basketball_shoot_007.mp4',
        '121'],
       ['/data1/hongn/haa500/video/washing_dishes/washing_dishes_000.mp4',
        '297'],
       ['/data1/hongn/haa500/video/snowboard_jump/snowboard_jump_010.mp4',
        '159'],
       ...,
       ['/data1/hongn/haa500/video/one_arm_push_up/one_arm_push_up_015.mp4',
        '155'],
       ['/data1/hongn/haa500/video/sprint_run/sprint_run_006.mp4', '395'],
       ['/data1/hongn/haa500/video/frisbee_catch/frisbee_catch_014.mp4',
        '432']], dtype='<U109')

In [88]:
y_train

array([121, 297, 159, ..., 155, 395, 432])

In [81]:
labels.astype(int)

array([  0,   0,   0, ..., 499, 499, 499])

In [69]:
import numpy as np
actioni = glob('/data1/hongn/haa500/video/gym_plank/*')
len(actioni)
np.ones(len(actioni)) * i

array([499., 499., 499., 499., 499., 499., 499., 499., 499., 499., 499.,
       499., 499., 499., 499., 499., 499., 499., 499., 499.])

In [68]:
all_data = pd.DataFrame(columns=['paths', 'labels'])
temp = np.stack([actioni, np.ones(len(actioni))], axis=1)
all_data = pd.concat([all_data,pd.Series(temp)], ignore_index=True)
all_data

ValueError: Data must be 1-dimensional, got ndarray of shape (20, 2) instead

In [7]:
actions[12]

'/data1/hongn/haa500/raw/play_ukulele.txt'